#
# Ensure BotFramework-Streaming library works in the browser by running tests after deploying a streaming-enabled JS Echo Bot and a React App that uses DLJS and WebChat.
# 

# "name" here defines the build number format. Build number is accessed via $(Build.BuildNumber)
name: $(Build.BuildId)
trigger: none
pr: none

pool:
  vmImage: 'windows-2019'

# TODO: variables
# BotName: defined in Azure
# AzureSubscription: defined in Azure
variables:
  runCodesignValidationInjection: false


stages:
  - stage: Deploy_Bot
    jobs:
      - job: Set_Dependency_To_Latest_BotBuilderJS_Daily_Version
        steps:
          - template: configure-to-bbjs-daily.yml
      
      - job: Install_Dependencies
        dependsOn:
          - Set_Dependency_To_Latest_BotBuilderJS_Daily_Version
        condition: succeeded()
        steps:
          - task: Npm@1
            displayName: 'npm install streaming echo bot dependencies'
            inputs: 
              workingDir: '$(System.DefaultWorkingDirectory)\libraries\streaming-e2e-tests\bot'
              verbose: false
      
      - job: Deploy_Streaming_Bot
        variables:
          BotProjectDir: '$(System.DefaultWorkingDirectory)\libraries\streaming-e2e-tests\bot'
          ResourceGroup: 'ash-streaming-js'
          BotName: 'ash-streaming-bot'
        dependsOn: Install_Dependencies
        steps:
          - template: deploy-bot.yml

