#
# Ensure BotFramework-Streaming library works in the browser by running tests after deploying a streaming-enabled JS Echo Bot and a React App that uses DLJS and WebChat.
# 

# "name" here defines the build number format. Build number is accessed via $(Build.BuildNumber)
name: $(Build.BuildId)
trigger: none
pr: none

pool:
  vmImage: 'windows-2019'

# TODO: variables
# BotName: defined in Azure
# AzureSubscription: defined in Azure
variables:
  runCodesignValidationInjection: false


stages:
  - stage: Deploy_Bot
    jobs:
      - job: Set_Dependency_To_Latest_BotBuilderJS_Daily_Version
        steps:
          - task: PowerShell@2
            displayName: 'Get latest botbuilder package version from MyGet - https://botbuilder.myget.org/gallery/botbuilder-v4-js-daily'
            inputs:
              targetType: 'filePath'
              filePath: $(System.DefaultWorkingDirectory)\libraries\streaming-e2e-tests\get-latest-bbjs-daily-version.ps1
              arguments:
                -AccessToken $(MyGetPersonalAccessToken)
                -WorkingDirectory $(System.DefaultWorkingDirectory)

          - task: colinsalmcorner.colinsalmcorner-buildtasks.tag-build-task.tagBuildOrRelease@0
            displayName: 'Tag Build with botbuilder version'
            inputs:
              tags: 'Using botbuilder version $(LatestVersion)'

          - task: PowerShell@2
            displayName: Set Dependency to Latest Version
            inputs:
                targetType: 'filePath'
                filePath: $(System.DefaultWorkingDirectory)\libraries\streaming-e2e-tests\set-dependency-version-in-packagejson.ps1
                arguments:
                  -LatestVersion $(LatestVersion)
                  -WorkingDirectory $(System.DefaultWorkingDirectory)

      - job: Create_npmrc_for_MyGet_Feed
        steps:
          - powershell: |
              Set-Location -Path "$(System.DefaultWorkingDirectory)\libraries\streaming-e2e-tests\bot"
              
              New-Item -Path . -Name ".npmrc" -ItemType "file" -Value "registry=https://botbuilder.myget.org/F/botbuilder-v4-js-daily/npm/"
            displayName: 'Create .npmrc for MyGet feed - https://botbuilder.myget.org/gallery/botbuilder-v4-js-daily'
      
      - job: Install_Dependencies
        dependsOn:
          - Set_Dependency_To_Latest_BotBuilderJS_Daily_Version
          - Create_npmrc_for_MyGet_Feed
        condition: succeeded()
        steps:
          - task: Npm@1
            displayName: 'npm install streaming echo bot dependencies'
            inputs: 
              workingDir: '$(System.DefaultWorkingDirectory)\libraries\streaming-e2e-tests\bot'
              verbose: false
      
      - job: Deploy_Streaming_Bot
        variables:
          BotProjectDir: '$(System.DefaultWorkingDirectory)\libraries\streaming-e2e-tests\bot'
          BotName: 'ash-streaming-js'
        dependsOn: Install_Dependencies
        steps:
          - template: deploy-bot.yml

