#
# Ensure BotFramework-Streaming library works in the browser by running tests after deploying a streaming-enabled JS Echo Bot and a React App that uses DLJS and WebChat.
# 

# "name" here defines the build number format. Build number is accessed via $(Build.BuildNumber)

name: $(Build.BuildId)
trigger: none
pr: none

pool:
  name: Azure Pipelines
  demands: npm
