#
# Ensure BotFramework-Streaming library works in the browser by running tests after deploying a streaming-enabled JS Echo Bot and a React App that uses DLJS and WebChat.
# 

# "name" here defines the build number format. Build number is accessed via $(Build.BuildNumber)
name: $(Build.BuildId)
trigger: none
pr: none

pool:
  vmImage: 'windows-2019'

# TODO: variables
# BotName: defined in Azure
variables:
  runCodesignValidationInjection: false


stages:
  - stage: Get_Latest_BotBuilderJS_Daily_Version
    jobs:
      - job: Get_Latest_BotBuilderJS_Daily_Version
        steps:
          - powershell: |
              $myGetPersonalAccessToken = "$(MyGetPersonalAccessToken)";
              $myGetFeedName = "botbuilder-v4-js-daily";
              $packageName = "botbuilder";
              
              $url = "https://botbuilder.myget.org/F/$myGetFeedName/auth/$myGetPersonalAccessToken/api/v2/feed-state";
              
              Write-Host "Get latest $packageName version number from MyGet $myGetFeedName";
              $result = Invoke-RestMethod -Uri $url -Method Get -ContentType "application/json";
              
              $package = $result.packages | Where-Object {$_.id -eq $packageName};
              [string]$latestVersion = $package.versions[-1];
              
              $package.id;
              $latestVersion;
              "##vso[task.setvariable variable=LatestVersion;]$latestVersion";
            displayName: 'Get latest botbuilder package version from MyGet - https://botbuilder.myget.org/gallery/botbuilder-v4-js-daily'

  - stage: Tag
    condition: succeededOrFailed()
    jobs:
      - job: Tag
        steps:
          - task: colinsalmcorner.colinsalmcorner-buildtasks.tag-build-task.tagBuildOrRelease@0
            displayName: 'Tag Build with botbuilder version'
            inputs:
              tags: 'Using botbuilder version $(LatestVersion)'

  - stage: Set_Dependency_To_Latest_Version
    jobs:
      - job: Set_Dependency_To_Latest_Version
        steps:
        - task: PowerShell@2
          inputs:
              targetType: 'filePath'
              filePath: $(System.DefaultWorkingDirectory)\libraries\streaming-e2e-tests\set-dependency-version-in-packagejson.ps1
              arguments:
                -LatestVersion 6.0.0
                -WorkingDirectory $(System.DefaultWorkingDirectory)
          displayName: Set Dependency to Latest Version
        
  