#
# Ensure BotFramework-Streaming library works in the browser by running tests after deploying a streaming-enabled JS Echo Bot and a React App that uses DLJS and WebChat.
# 

# "name" here defines the build number format. Build number is accessed via $(Build.BuildNumber)
name: $(Build.BuildId)
trigger: none
pr: none

pool:
  vmImage: 'windows-2019'

# TODO: variables
# BotName: defined in Azure
variables:
  runCodesignValidationInjection: false


stages:
  - stage: Get_Latest_BotBuilderJS_Daily_Version
    jobs:
      - job: Get_Latest_BotBuilderJS_Daily_Version
        steps:
          - task: PowerShell@2
            inputs:
              targetType: 'filePath'
              filePath: $(System.DefaultWorkingDirectory)\libraries\streaming-e2e-tests\get-latest-bbjs-daily-version.ps1
              arguments:
                -AccessToken $(MyGetPersonalAccessToken)
                -WorkingDirectory $(System.DefaultWorkingDirectory)
            displayName: 'Get latest botbuilder package version from MyGet - https://botbuilder.myget.org/gallery/botbuilder-v4-js-daily'

          - task: colinsalmcorner.colinsalmcorner-buildtasks.tag-build-task.tagBuildOrRelease@0
            displayName: 'Tag Build with botbuilder version'
            inputs:
              tags: 'Using botbuilder version $(LatestVersion)'
              
          - task: PowerShell@2
            inputs:
                targetType: 'filePath'
                filePath: $(System.DefaultWorkingDirectory)\libraries\streaming-e2e-tests\set-dependency-version-in-packagejson.ps1
                arguments:
                  -LatestVersion $(LatestVersion)
                  -WorkingDirectory $(System.DefaultWorkingDirectory)
            displayName: Set Dependency to Latest Version
        
  